#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DEVICE=a500

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
#PRODUCT_COPY_FILES += \\
#    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libcamera.so:obj/lib/libcamera.so \\

# All the blobs necessary for a500
PRODUCT_COPY_FILES += \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/asound.conf:/system/etc/asound.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gps.conf:/system/etc/gps.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/media_profiles.xml:/system/etc/media_profiles.xml \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/nvram.txt:/system/etc/nvram.txt \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/vold.fstab:/system/etc/vold.fstab \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/bcm4329.hcd:/system/etc/firmware/bcm4329.hcd \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvddk_audiofx_core.axf:/system/etc/firmware/nvddk_audiofx_core.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvddk_audiofx_transport.axf:/system/etc/firmware/nvddk_audiofx_transport.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_aacdec.axf:/system/etc/firmware/nvmm_aacdec.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_adtsdec.axf:/system/etc/firmware/nvmm_adtsdec.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_audiomixer.axf:/system/etc/firmware/nvmm_audiomixer.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_h264dec.axf:/system/etc/firmware/nvmm_h264dec.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_jpegdec.axf:/system/etc/firmware/nvmm_jpegdec.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_jpegenc.axf:/system/etc/firmware/nvmm_jpegenc.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_manager.axf:/system/etc/firmware/nvmm_manager.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_mp2dec.axf:/system/etc/firmware/nvmm_mp2dec.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_mp3dec.axf:/system/etc/firmware/nvmm_mp3dec.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_mpeg4dec.axf:/system/etc/firmware/nvmm_mpeg4dec.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_reference.axf:/system/etc/firmware/nvmm_reference.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_service.axf:/system/etc/firmware/nvmm_service.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_sorensondec.axf:/system/etc/firmware/nvmm_sorensondec.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_vc1dec.axf:/system/etc/firmware/nvmm_vc1dec.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_wavdec.axf:/system/etc/firmware/nvmm_wavdec.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_wmadec.axf://system/etc/firmware/nvmm_wmadec.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvmm_wmaprodec.axf://system/etc/firmware/nvmm_wmaprodec.axf \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/nvrm_avp.bin:/system/etc/firmware/nvrm_avp.bin \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/gpsconfig.xml:/system/etc/gps/gpsconfig.xml \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libEGL_tegra.so:/system/lib/egl/libEGL_tegra.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libGLESv1_CM_tegra.so:/system/lib/egl/libGLESv1_CM_tegra.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libGLESv2_tegra.so:/system/lib/egl/libGLESv2_tegra.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/gps.tegra.so:/system/lib/hw/gps.tegra.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/gralloc.tegra.so:/system/lib/hw/gralloc.tegra.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/hwcomposer.tegra.so:/system/lib/hw/hwcomposer.tegra.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/lights.picasso.so:/system/lib/hw/lights.picasso.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/overlay.tegra.so:/system/lib/hw/overlay.tegra.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/sensors.tegra.so:/system/lib/hw/sensors.tegra.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/tegra_alsa.tegra.so:/system/lib/hw/tegra_alsa.tegra.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libWVStreamControlAPI.so:/system/lib/libWVStreamControlAPI.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/liba2dp.so:/system/lib/liba2dp.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libaceralbum.so:/system/lib/libaceralbum.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libasound.so:/system/lib/libasound.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libaudio.so:/system/lib/libaudio.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libaudiopolicy.so:/system/lib/libaudiopolicy.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libcaps.so:/system/lib/libcaps.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libcgdrv.so:/system/lib/libcgdrv.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libdec.so:/system/lib/libdec.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libgetsourceid.so:/system/lib/libgetsourceid.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libhtml2xhtml.so:/system/lib/libhtml2xhtml.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libhtml2xhtml.so:/system/lib/libhtml2xhtml.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libhwui.so:/system/lib/libhwui.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libjni_xt9input.so:/system/lib/libjni_xt9input.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libmllite.so:/system/lib/libmllite.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libmlplatform.so:/system/lib/libmlplatform.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libmpl.so:/system/lib/libmpl.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvddk_2d.so:/system/lib/libnvddk_2d.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvddk_2d_v2.so:/system/lib/libnvddk_2d_v2.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvddk_aes_user.so:/system/lib/libnvddk_aes_user.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvddk_audiofx.so:/system/lib/libnvddk_audiofx.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvddk_vmr.so:/system/lib/libnvddk_vmr.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvdispatch_helper.so:/system/lib/libnvdispatch_helper.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvdispmgr_d.so:/system/lib/libnvdispmgr_d.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvec.so:/system/lib/libnvec.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm.so:/system/lib/libnvmm.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm.so:/system/lib/libnvmm.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_asfparser.so:/system/lib/libnvmm_asfparser.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_audio.so:/system/lib/libnvmm_audio.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_aviparser.so:/system/lib/libnvmm_aviparser.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_camera.so:/system/lib/libnvmm_camera.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libcamera.so:/system/lib/libcamera.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_contentpipe.so:/system/lib/libnvmm_contentpipe.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_image.so:/system/lib/libnvmm_image.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_manager.so:/system/lib/libnvmm_manager.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_misc.so:/system/lib/libnvmm_misc.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/:/system/lib/libnvmm_msaudio.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_parser.so:/system/lib/libnvmm_parser.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_service.so:/system/lib/libnvmm_service.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_tracklist.so:/system/lib/libnvmm_tracklist.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_utils.so:/system/lib/libnvmm_utils.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_vc1_video.so:/system/lib/libnvmm_vc1_video.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_video.so:/system/lib/libnvmm_video.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_videorenderer.so:/system/lib/libnvmm_videorenderer.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_videorenderer.so:/system/lib/libnvmm_videorenderer.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_vp6_video.so:/system/lib/libnvmm_vp6_video.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/:/system/lib/libnvmm_writer.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvmm_writer.so:/system/lib/libnvmm_writer.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvodm_dtvtuner.so:/system/lib/libnvodm_dtvtuner.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvodm_imager.so:/system/lib/libnvodm_imager.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvodm_query.so:/system/lib/libnvodm_query.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvomx.so:/system/lib/libnvomx.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvomxilclient.so:/system/lib/libnvomxilclient.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvos.so:/system/lib/libnvos.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvrm.so:/system/lib/libnvrm.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvrm_channel.so:/system/lib/libnvrm_channel.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvrm_graphics.so:/system/lib/libnvrm_graphics.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvrm_graphics.so:/system/lib/libnvrm_graphics.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvsm.so:/system/lib/libnvsm.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvtestio.so:/system/lib/libnvtestio.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvtestresults.so:/system/lib/libnvtestresults.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libnvwsi.so:/system/lib/libnvwsi.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libpdfhost_pre.so:/system/lib/libpdfhost_pre.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/librmsdkplatform_presys.so:/system/lib/librmsdkplatform_presys.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libstabilize.so:/system/lib/libstabilize.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libstagefrighthw.so:/system/lib/libstagefrighthw.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libstream_core.so:/system/lib/libstream_core.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libtalk_jni.so:/system/lib/libtalk_jni.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libttssynthproxy.so:/system/lib/libttssynthproxy.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libvoicesearch.so:/system/lib/libvoicesearch.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libwvdrm.so:/system/lib/libwvdrm.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/libwvm.so:/system/lib/libwvm.so \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/atmel-maxtouch.idc:/system/usr/idc/atmel-maxtouch.idc \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/panjit_touch.idc:/system/usr/idc/panjit_touch.idc \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/Acer-AK00LB.kcm:/system/usr/keychars/Acer-AK00LB.kcm \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/Acer-AK00LB.kl:/system/usr/keylayout/Acer-AK00LB.kl \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/acer-dock.kl:/system/usr/keylayout/acer-dock.kl \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/gpio-keys.kl:/system/usr/keylayout/gpio-keys.kl \\
    vendor/$MANUFACTURER/__DEVICE__/proprietary/glgps_nvidiaTegra2android:/system/bin/glgps_nvidiaTegra2android
EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/acer/$DEVICE/$DEVICE-vendor.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/acer/__DEVICE__/setup-makefiles.sh

# Live wallpaper packages
PRODUCT_PACKAGES += \\
    LiveWallpapers \\
    LiveWallpapersPicker \\
    MagicSmokeWallpapers \\
    VisualizationWallpapers

# Publish that we support the live wallpaper feature.
PRODUCT_COPY_FILES += \\
    packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:/system/etc/permissions/android.software.live_wallpaper.xml

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS := vendor/acer/__DEVICE__/overlay

\$(call inherit-product, vendor/acer/__DEVICE__/__DEVICE__-vendor-blobs.mk)
EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/acer/$DEVICE/BoardConfigVendor.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/acer/__DEVICE__/setup-makefiles.sh

USE_CAMERA_STUB := false
EOF
